### ISSUE TITLE
[Feature Request] An option to select a random skin without user interaction

### ISSUE THREAD

**Issue by Tatrii** [LewisConor/Random-Skin-Selector#2]
I'm usually pushing the clock in champ select setting up my rune page 😂 I think it would be awesome if after selecting a champ the script would automatically run 😁

**Comment by LewisConor** [comment]
Now that is an intriguing suggestion. I'll see what I can do and get back to you on that. Thanks for suggestion.

**Comment by LewisConor** [comment]
New Version now available with an Auto Randomizer Mode.
